#!/bin/bash
. ./cluster_config.sh

## prepare the config file template
python ./prepareConfTemplate.py "${__IP_ADDRESSES[*]}" $__DISCOVERY_PORT $__CONF_TEMP_BASE_NAME > $__CONF_TEMP_NAME
data_copy=$1
## initialize the cluster
if [[ $data_copy == "yes" ]]; then
   bash init-cluster.sh
fi

## initialize the machines (aka groups)
####### Generate configuration files
./cbash -s "bash ./$__BIN_DIR_NAME/init-group.sh"

####### Prepare the binary
#./cbash -s "bash ./git-operation.sh -c"
#./cbash -s "bash ./git-operation.sh -p"
#./cbash -s "bash ./git-operation.sh -cm"
#./cbash -s "bash ./git-operation.sh -m"

####### TODO : 

