/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_srch2_Srch2EngineTest */

#ifndef _Included_com_srch2_Srch2EngineTest
#define _Included_com_srch2_Srch2EngineTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_srch2_Srch2EngineTest
 * Method:    createSearchableEngine
 * Signature: (Ljava/lang/Class;Ljava/lang/reflect/Method;)J
 */
JNIEXPORT jlong JNICALL Java_com_srch2_Srch2EngineTest_createSearchableEngine
  (JNIEnv *, jobject, jclass, jobject);

/*
 * Class:     com_srch2_Srch2EngineTest
 * Method:    setString
 * Signature: (JLcom/srch2/SearchableString;)V
 */
JNIEXPORT void JNICALL Java_com_srch2_Srch2EngineTest_setString
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_srch2_Srch2EngineTest
 * Method:    getString
 * Signature: (J)Lcom/srch2/SearchableString;
 */
JNIEXPORT jobject JNICALL Java_com_srch2_Srch2EngineTest_getString
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
