/*
 * Copyright (c) 2016, SRCH2
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *    * Redistributions of source code must retain the above copyright
 *      notice, this list of conditions and the following disclaimer.
 *    * Redistributions in binary form must reproduce the above copyright
 *      notice, this list of conditions and the following disclaimer in the
 *      documentation and/or other materials provided with the distribution.
 *    * Neither the name of the SRCH2 nor the
 *      names of its contributors may be used to endorse or promote products
 *      derived from this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL SRCH2 BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_srch2_StringEngine */

#ifndef _Included_com_srch2_StringEngine
#define _Included_com_srch2_StringEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_srch2_StringEngine
 * Method:    createStringEngine
 * Signature: (Ljava/lang/reflect/Method;
               Ljava/lang/Class; Ljava/lang/reflect/Constructor;
               Ljava/lang/Class; Ljava/lang/reflect/Constructor)J
 */
JNIEXPORT jlong JNICALL Java_com_srch2_StringEngine_createStringEngine
  (JNIEnv *, jclass, jobject,
   jclass, jobject, jclass, jobject, jclass, jobject);

/*
 * Class:     com_srch2_StringEngine
 * Method:    setString
 * Signature: (JLcom/srch2/Attribute;)V
 */
JNIEXPORT void JNICALL Java_com_srch2_StringEngine_setString
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_srch2_StringEngine
 * Method:    getSearchableString
 * Signature: (J)Lcom/srch2/SearchableString;
 */
JNIEXPORT jobject JNICALL Java_com_srch2_StringEngine_getSearchableString
  (JNIEnv *, jclass, jlong);
/*
 * Class:     com_srch2_StringEngine
 * Method:    getRefiningString
 * Signature: (J)Lcom/srch2/RefiningString;
 */
JNIEXPORT jobject JNICALL Java_com_srch2_StringEngine_getRefiningString
  (JNIEnv *, jclass, jlong);
/*
 * Class:     com_srch2_StringEngine
 * Method:    getIndexedString
 * Signature: (J)Lcom/srch2/IndexedString;
 */
JNIEXPORT jobject JNICALL Java_com_srch2_StringEngine_getIndexedString
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_srch2_StringEngine
 * Method:    deleteRefiningEngine
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_srch2_StringEngine_deleteStringEngine
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif

