
/*****************************************************************************
 *                                                                           *
 *              AUTHOR : RJ ATWAL                                            *
 *                                                                           *
 *                                                                           * 
  ****************************************************************************/

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_srch2_StringEngine */

#ifndef _Included_com_srch2_StringEngine
#define _Included_com_srch2_StringEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_srch2_StringEngine
 * Method:    createStringEngine
 * Signature: (Ljava/lang/reflect/Method;
               Ljava/lang/Class; Ljava/lang/reflect/Constructor;
               Ljava/lang/Class; Ljava/lang/reflect/Constructor)J
 */
JNIEXPORT jlong JNICALL Java_com_srch2_StringEngine_createStringEngine
<<<<<<< HEAD:test/java/sdk/unit/string/jni/com_srch2_StringEngine.h
  (JNIEnv *, jclass, jobject,
   jclass, jobject, jclass, jobject, jclass, jobject);

/*
 * Class:     com_srch2_StringEngine
 * Method:    setString
 * Signature: (JLcom/srch2/Attribute;)V
 */
JNIEXPORT void JNICALL Java_com_srch2_StringEngine_setString
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_srch2_StringEngine
 * Method:    getSearchableString
 * Signature: (J)Lcom/srch2/SearchableString;
 */
JNIEXPORT jobject JNICALL Java_com_srch2_StringEngine_getSearchableString
  (JNIEnv *, jclass, jlong);
/*
 * Class:     com_srch2_StringEngine
 * Method:    getRefiningString
 * Signature: (J)Lcom/srch2/RefiningString;
 */
JNIEXPORT jobject JNICALL Java_com_srch2_StringEngine_getRefiningString
  (JNIEnv *, jclass, jlong);
/*
 * Class:     com_srch2_StringEngine
 * Method:    getIndexedString
 * Signature: (J)Lcom/srch2/IndexedString;
 */
JNIEXPORT jobject JNICALL Java_com_srch2_StringEngine_getIndexedString
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_srch2_StringEngine
 * Method:    deleteRefiningEngine
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_srch2_StringEngine_deleteStringEngine
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif

